name: Run Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Consider using a stable version of Python

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev
          # Install TA-Lib dependencies
          sudo apt-get install -y libta-lib0 libta-lib-dev
          # Install Python package tools using pip
          python -m pip install --upgrade pip setuptools wheel
          # Install TA-Lib Python package using pip
          pip install ta-lib
          # Install other project dependencies
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest
