name: Run Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev wget
          # Download and install TA-Lib from source
          wget https://github.com/mrjbq7/ta-lib/archive/refs/tags/0.4.0.tar.gz
          tar -xzf 0.4.0.tar.gz
          cd ta-lib-0.4.0
          ./configure --prefix=/usr
          make
          sudo make install
          cd ..
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest
