name: Run Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev
          # Clone TA-Lib from the official repository
          git clone https://github.com/TA-Lib/ta-lib-python.git
          cd ta-lib-python
          # Install TA-Lib from source
          python setup.py install
          cd ..
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest
