name: Run Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev wget

      - name: Install TA-Lib C Library
        run: |
          # Download and extract TA-Lib source
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib/
          
          # Configure and install TA-Lib
          ./configure --prefix=/usr
          make
          sudo make install
          
      - name: Install Python dependencies including TA-Lib
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install ta-lib
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest
